### ISSUE TITLE
update doc install

### ISSUE THREAD

**Issue by AlbanMinassian** [saiumesh535/npm-dep-chek-rust#2]
Missing section "Install" :

- need rust, see <https://rustup.rs/>
- git clone https://github.com/saiumesh535/npm-dep-chek-rust.git
- cd npm-dep-chek-rust
- cargo install --path .

Alban

**Comment by saiumesh-apty** [comment]
Hey @AlbanMinassian  you can download executable from release assets. https://github.com/saiumesh535/npm-dep-chek-rust#installation

**Comment by AlbanMinassian** [comment]
Hello @saiumesh-apty.
As new user, a link to <https://github.com/saiumesh535/npm-dep-chek-rust/releases> will be helpfull.

Why not this section "Install" :

    Goto [release](https://github.com/saiumesh535/npm-dep-chek-rust/releases) and download latest version from assets.
    or build: 

    - need rust, see https://rustup.rs/    - 
    - git clone https://github.com/saiumesh535/npm-dep-chek-rust.git
    - cd npm-dep-chek-rust
    - cargo install --path .

Alban

**Comment by saiumesh535** [comment]
Hey @AlbanMinassian do you mind creating a PR ?

**Comment by AlbanMinassian** [comment]
yes

**Comment by AlbanMinassian** [comment]
PR https://github.com/saiumesh535/npm-dep-chek-rust/pull/3
